# Generated by Django 4.1.4 on 2023-07-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_hoteladdress_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoteladdress',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hoteladdress',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
