# Generated by Django 4.1.4 on 2023-07-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportaddress',
            name='address',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
