# Generated by Django 4.1.4 on 2023-07-08 08:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import utlis.validation_transport_date
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Railway_station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='railwayAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must not consist of space and requires country code. eg : 989210000000', regex='^[1-9][0-9]{8,14}$')])),
                ('address', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_number', models.IntegerField(default=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('max_reservation', models.PositiveSmallIntegerField()),
                ('number_reserved', models.PositiveSmallIntegerField(default=0)),
                ('transfer_date', models.DateTimeField(validators=[utlis.validation_transport_date.validation_transport_date])),
                ('duration', models.TimeField()),
                ('transport_status', models.CharField(choices=[('SPACE', 'Space'), ('FULL', 'Full'), ('TRANSFER', 'Transfer'), ('ARRIVED', 'Arrived'), ('CANCELLED', 'Cancelled')], default='SPACE', max_length=15)),
                ('is_valid', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination', to='train.railway_station')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source', to='train.railway_station')),
            ],
            options={
                'ordering': ['-transport_number'],
            },
        ),
        migrations.CreateModel(
            name='TrainSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('INITIAL', 'Initial'), ('FREE', 'Free'), ('RESERVED', 'Reserved'), ('PROBLEM', 'Problem')], default='FREE', max_length=10)),
                ('price', models.PositiveBigIntegerField(blank=True, default=0)),
                ('is_valid', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('Train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat', to='train.train')),
            ],
        ),
        migrations.CreateModel(
            name='TrainReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('guests', models.PositiveSmallIntegerField()),
                ('reserved_status', models.CharField(choices=[('INITIAL', 'Initial'), ('RESERVED', 'Reserved'), ('CANCELLED', 'Cancelled'), ('FINISHED', 'Finished'), ('PROBLEM', 'Problem')], default='INITIAL', max_length=15)),
                ('is_valid', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('passenger_count', models.PositiveSmallIntegerField()),
                ('Train', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Train_reservation', to='train.train')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrainPassenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_code', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('reserved_key', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must not consist of space and requires country code. eg : 989210000000', regex='^[1-9][0-9]{8,14}$')])),
                ('birth_day', models.DateField()),
                ('national_id', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('passenger_type', models.CharField(choices=[('ADULT', 'Adult'), ('CHILDREN', 'Children')], default='ADULT', max_length=20)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('transfer_status', models.CharField(choices=[('INITIAL', 'Initial'), ('RESERVED', 'Reserved'), ('TRANSFER', 'Transfer'), ('ARRIVED', 'Arrived'), ('CANCELLED', 'Cancelled')], default='INITIAL', max_length=20)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat', to='train.trainseat')),
            ],
        ),
        migrations.AddField(
            model_name='railway_station',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Railway_station', to='train.railwayaddress'),
        ),
        migrations.AddConstraint(
            model_name='trainseat',
            constraint=models.UniqueConstraint(fields=('Train', 'number'), name='unique_Train_seat'),
        ),
        migrations.AddConstraint(
            model_name='trainpassenger',
            constraint=models.UniqueConstraint(condition=models.Q(('transfer_status__in', ['INITIAL', 'RESERVED', 'TRANSFER'])), fields=('seat', 'national_id'), name='unique_TrainSeat_user'),
        ),
    ]
