# Generated by Django 4.1.4 on 2023-07-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0002_alter_railwayaddress_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='duration',
        ),
        migrations.AddField(
            model_name='train',
            name='back_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='train',
            name='transfer_date',
            field=models.DateField(blank=True),
        ),
    ]
